2024-02-19 11:45:47,025 - 15 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2024-02-19 11:45:47,046 - 15 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-02-19 11:45:47,050 - 15 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-02-19 11:45:47,104 - 15 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Changing position mode to ONEWAY succeeded.
2024-02-19 11:45:48,204 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-19 11:45:48,205 - 15 - hummingbot.connector.exchange.whitebit.whitebit_exchange.WhitebitExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-19 11:45:48,443 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Leverage for XMR-USDT successfully set to 1.
2024-02-19 11:45:48,585 - 15 - hummingbot.connector.exchange.whitebit.whitebit_api_user_stream_data_source.WhitebitAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 45, in listen_for_user_stream
    self._ws_assistant = await self._connected_websocket_assistant()
  File "/home/hummingbot/hummingbot/connector/exchange/whitebit/whitebit_api_user_stream_data_source.py", line 35, in _connected_websocket_assistant
    token_response = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 58, in execute_request
    response_json = await response.json()
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/data_types.py", line 114, in json
    json_ = await self._aiohttp_response.json()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1164, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://whitebit.com/api/v4/profile/websocket_token')
2024-02-19 11:45:48,796 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for XMR-USDT. 1/1 completed.
2024-02-19 11:45:48,797 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key CC4AF6dsUoCDdwxw2cq2Fitrkw0znyaiAZmeY8yx2ghs9nCKjJA2TdO5y4IDo44B
2024-02-19 11:45:48,801 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2024-02-19 11:45:48,913 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for XMR-USDT. 1/1 completed.
2024-02-19 11:45:48,978 - 15 - hummingbot.connector.exchange.whitebit.whitebit_api_order_book_data_source.WhitebitAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-02-19 11:45:49,589 - 15 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on api/v4/profile/websocket_token (1 calls per 10s) has almost reached. Limits used is 1 in the last 10 seconds
2024-02-19 11:45:52,808 - 15 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-02-19 11:45:58,674 - 15 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-02-19 11:45:59,035 - 15 - hummingbot.connector.exchange.whitebit.whitebit_api_user_stream_data_source.WhitebitAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 45, in listen_for_user_stream
    self._ws_assistant = await self._connected_websocket_assistant()
  File "/home/hummingbot/hummingbot/connector/exchange/whitebit/whitebit_api_user_stream_data_source.py", line 35, in _connected_websocket_assistant
    token_response = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 58, in execute_request
    response_json = await response.json()
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/data_types.py", line 114, in json
    json_ = await self._aiohttp_response.json()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1164, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://whitebit.com/api/v4/profile/websocket_token')
2024-02-19 11:46:05,816 - 15 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-02-19 11:46:08,299 - 15 - hummingbot.client.hummingbot_application - ERROR - MQTT is already stopped!
2024-02-19 11:46:08,300 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Return value already set. Application.exit() failed.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/exit_command.py", line 38, in exit_loop
    self.app.exit()
  File "/home/hummingbot/hummingbot/client/ui/hummingbot_cli.py", line 202, in exit
    self.app.exit()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1086, in exit
    raise Exception("Return value already set. Application.exit() failed.")
Exception: Return value already set. Application.exit() failed.
2024-02-19 14:41:30,229 - 15 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-02-19 14:41:30,234 - 15 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-02-19 14:41:30,311 - 15 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Changing position mode to ONEWAY succeeded.
2024-02-19 14:41:31,046 - 15 - hummingbot.connector.exchange.whitebit.whitebit_exchange.WhitebitExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-19 14:41:31,696 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-19 14:41:31,886 - 15 - hummingbot.connector.exchange.whitebit.whitebit_api_order_book_data_source.WhitebitAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-02-19 14:41:31,949 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Leverage for XMR-USDT successfully set to 1.
2024-02-19 14:41:32,024 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No order book exists for 'XMR-USDT'.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/status_command.py", line 152, in status_check_all
    self.notify(await self.strategy_status())
  File "/home/hummingbot/hummingbot/client/command/status_command.py", line 76, in strategy_status
    st_status = await self.strategy.format_status()
  File "/home/hummingbot/hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 453, in format_status
    buy_price = await market.get_quote_price(trading_pair, True, self._order_amount)
  File "hummingbot/connector/exchange_base.pyx", line 358, in get_quote_price
    return Decimal(str(self.get_vwap_for_volume(trading_pair, is_buy, amount).result_price))
  File "hummingbot/connector/exchange_base.pyx", line 256, in hummingbot.connector.exchange_base.ExchangeBase.get_vwap_for_volume
    return self.c_get_vwap_for_volume(trading_pair, is_buy, volume)
  File "hummingbot/connector/exchange_base.pyx", line 169, in hummingbot.connector.exchange_base.ExchangeBase.c_get_vwap_for_volume
    OrderBook order_book = self.c_get_order_book(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 151, in hummingbot.connector.exchange_base.ExchangeBase.c_get_order_book
    return self.get_order_book(trading_pair)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 244, in get_order_book
    raise ValueError(f"No order book exists for '{trading_pair}'.")
ValueError: No order book exists for 'XMR-USDT'.
2024-02-19 14:41:32,247 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2024-02-19 14:41:32,366 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key yGvuuHfPXHDcqTYBGx4LjSI07NopGVPZVyywYzGxFEn6pfibgxUuBN3W22hNzcZf
2024-02-19 14:41:32,636 - 15 - hummingbot.connector.exchange.whitebit.whitebit_api_user_stream_data_source.WhitebitAPIUserStreamDataSource - INFO - Subscribed to private order changes and balance updates channels...
2024-02-19 14:41:34,006 - 15 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Markets are ready.
2024-02-19 14:41:34,007 - 15 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Trading started.
2024-02-19 14:41:34,007 - 15 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - There is an existing XMR-USDT BOTH position. The bot resumes operation to close out the arbitrage position
2024-02-19 14:54:00,082 - 15 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-02-19 15:01:23,273 - 15 - hummingbot.client.hummingbot_application - ERROR - MQTT is already stopped!
2024-02-19 15:01:23,275 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Return value already set. Application.exit() failed.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/exit_command.py", line 38, in exit_loop
    self.app.exit()
  File "/home/hummingbot/hummingbot/client/ui/hummingbot_cli.py", line 202, in exit
    self.app.exit()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1086, in exit
    raise Exception("Return value already set. Application.exit() failed.")
Exception: Return value already set. Application.exit() failed.
2024-02-19 15:01:23,276 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Return value already set. Application.exit() failed.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/exit_command.py", line 38, in exit_loop
    self.app.exit()
  File "/home/hummingbot/hummingbot/client/ui/hummingbot_cli.py", line 202, in exit
    self.app.exit()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 1086, in exit
    raise Exception("Return value already set. Application.exit() failed.")
Exception: Return value already set. Application.exit() failed.
